name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  vpc:
    if: contains(github.event.head_commit.message, '') || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/vpc

    steps:
      - uses: actions/checkout@v4

      - name: Run only if VPC changed
        run: |
          git diff --name-only HEAD~1 HEAD | grep '^infra/vpc/' || exit 0

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan

  ec2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/ec2

    steps:
      - uses: actions/checkout@v4

      - name: Run only if EC2 changed
        run: |
          git diff --name-only HEAD~1 HEAD | grep '^infra/ec2/' || exit 0

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan

  s3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/s3

    steps:
      - uses: actions/checkout@v4

      - name: Run only if S3 changed
        run: |
          git diff --name-only HEAD~1 HEAD | grep '^infra/s3/' || exit 0

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform plan
